language: go

go:
  - 1.8.x
  - 1.9
  - master

# Skip the install step. Don't `go get` dependencies. Only build with the
# code in vendor/
install: true

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: tip

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  make test