language: go
go:
- 1.9
- master
- tip
install: true
matrix:
  allow_failures:
  - go: master
  - go: tip
notifications:
  email: false
script: make test
before_deploy:
- make build v=nightly
- go run nightly.go
deploy:
  target_commitish: $TRAVIS_COMMIT
  provider: releases
  api_key:
    secure: r8RatJXfzVq3tug6Rn5o3TAfpXBPhKsTToGrQJotyAkH46Btx3I+EafqFFwRxvej9mASFIRpRKLQMDXelv3jgDGutNISk/4Ug84JSGcPe0GWyw22Ic5RA2AjjhPzHQszDuGnoAgwlgruBKdIpa3Efr4rpGUFI3VoSlmSdfQqIOPK2jXPYZ6ewAGemCJZQkFZjF35rLRwCrd2EycMg1elnj9I+JXpG4ghDF7reFv/dZaN4JwG4RTps6SO4KZYvxo4hY/EGjFF1HqtUzImJah9dL0pJ9H37IjwAhXYKd+ucN7yYm5QPPjr0rXuD8iIqtwTYKO7A+Wg9vxCh7rfLivKJKP3l0A6i0+FXB1pXL2q4At6/TXQwIBgVIy7A50YkLt167MuRFHyuS12Xh4RKzLurLKdcp+Mn/ve38RkZlZOe4VDEfg+KPaInRqdZbC/fR7NCoUpRB5Dijt93fWs0wbr03gK50RvsKd/uMsQ1dIzvXGawvS8T4m5CSBi6TQ3G8r00DfWwWtqPniy6iZoZR9bryEFy7O1RkbDbPsp1FbZg+FrkBQnE8vdhFAuNd9Bd8MdTnMrcDVLwAtAdGLcOwEB1kjbsZmHFI9Un5HPoMSoPMsG4NJlXXb4ngKHvQ0//92wUOc/cj9Sm1ilj79K9qZX2BU48S9FLD57HE5TqyH0hzw=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  tag_name: nightly
  overwrite: true
  on:
    branch: master
    repo: socialplanner/instahelper
    tags: false
    go: 1.9
  name: Nightly
  body: Nightly release built on the latest commit to the repo.
  prerelease: true
  draft: false
cache:
  directories:
  - vendor

env:
  global:
    secure: aVi6QR58c9qqomWGG92/0Px6OfA8l3wBDJ9VYl2IMoY0QmjVO42o1K5RznBfhWw5csFY7jkMjqxWb53f/Ovg3vJPiJxqnLTcGgZOk8AAC4zC1S1nO9RKnf4Wwze2ctvt5AUKLXQCyBf0Qmgd2OFNIeglNKBo65Npqqx1ys335jLZHJtaXn+2GTguqDXfjKjZI/hXYpgOkmVMpQZyw5Na+BvCvpMBcsT8QbUiB1Xhlj1KXXEXdTij4h1rRj6JqS3Wjkdjxn2ykOMk0bluGMdQxlUtvvuHP5FJbeYW+W6uUYcMkiMfsLlmzl0GtIdTKokhYkZ0+m+JygTYlYapVv0lO61yYCvSOOeCiOlvUSdSU7IMnIaLe1NOcEU38/99r3bTQRlKuvzqJMddpjyGNGbrs8xDvSMhOrxyN8bNk+wuUx9oAVIA02luX/UP+Yh9Xh2b/VBUnARAd24M4eqQTqNnjPdKGOGqSRcFBYH1cBmsjndj6U9RIzhgUmhvBr9Q3kCciw+cOMmiRDvbQzd7SamELlYEuy6DFyqCZOhx2KJUFPIh9VerSmOgH5jjBipJVOx/OK65shfWNx3yYUR1GSWFu7wxoUVgvUZ620lnIHT79c6fztIo4RWo5SOpWjOEHizSFTtXGuXH0BYXXMEmWtbSp/pH8MoGPSRj7TKPFid2ypE=
